config/routes.rb
Rails.application.routes.draw do
  root to: 'session#new'
  get '/auth/:provider/callback', to: 'session#create'
  get "/signout", to: 'session#destroy'

  resources :boards do
    member do
      get 'copy'
    end
  end

  get 'kb/:id' => 'kanbans#board', as: :kanban_board
  post 'kb/:id/move' => 'kanbans#move_card', as: :move_card

end

app/models/board.rb
class Board < ActiveRecord::Base
  extend FriendlyId
  friendly_id :user_and_name, use: :slugged

  belongs_to :user

  has_many :repositories, inverse_of: :board, dependent: :delete_all
  has_many :stages, -> { order "ui_sort_order" }, inverse_of: :board, dependent: :delete_all

  accepts_nested_attributes_for :repositories, allow_destroy: true
  accepts_nested_attributes_for :stages, allow_destroy: true

  validates :name, presence: true
  validates :name, uniqueness: { scope: :user, case_sensitive: false }

  def user_and_name
    "#{user.nickname}-#{name}"
  end

  def should_generate_new_friendly_id?
    name_changed? || super
  end
end

app/models/card.rb
class Card
  # include ActiveModel::Model
  include ActiveModel::Serialization

  attr_accessor :title, :number, :html_url, :stage, :assignee, :assignee_avatar_url, :labels, :repo_url, :is_pull_request

  def initialize()
    self.labels = []
  end

  def attributes
    {
      title: nil,
      number: nil,
      html_url: nil,
      labels: nil,
      stage: nil,
      assignee: nil,
      assignee_avatar_url:nil,
      repo_url: nil,
      is_pull_request: nil
    }
  end
end

app/models/repository.rb
class Repository < ActiveRecord::Base
  belongs_to :board, inverse_of: :repositories

  validates :url, presence: true

  def has_no_milestone?
    repo.milestone.nil?
  end
end

app/models/stage.rb
class Stage < ActiveRecord::Base
  attr_accessor :cards

  belongs_to :board, inverse_of: :stages

  validates :name, :github_label, presence: true

  after_initialize :init

  def init
    self.cards = []
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :boards

  def self.find_or_create_from_auth_hash(auth_hash)
    user = User.where(provider: auth_hash['provider'], uid: auth_hash['uid']).first
    if user.nil?
      user = create! do |user|
        user.provider = auth_hash['provider']
        user.uid = auth_hash['uid']
        user.name = auth_hash['info']['name'] || auth_hash['info']['nickname']
        user.token = auth_hash['credentials']['token']
        user.nickname = auth_hash['info']['nickname']
        user.email = auth_hash['info']['email']
        user.image_url = auth_hash['info']['image']
      end
    else
      user.token = auth_hash['credentials']['token']
      user.name = auth_hash['info']['name'] || auth_hash['info']['nickname']
      user.nickname = auth_hash['info']['nickname']
      user.email = auth_hash['info']['email']
      user.image_url = auth_hash['info']['image']
      user.save!
    end

    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  protected

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  include Authenticator
  before_action :reset_return_to, only: [:index, :new, :show, :destroy]

  def index
    session[:return_to] = nil
    @boards = Board.includes(:user).where(user: current_user).where(is_public: false).order(:name)
    @public_boards = Board.includes(:user).where(is_public: true).order(:name)
  end

  def new
    @board = Board.new
    defaults = {'stage:in-queue' => 'In Queue',
      'stage:development' => 'Development',
      'stage:testing' => 'Testing',
      'stage:testing-done' => 'Testing Done',
      'stage:ready-to-release' => 'Ready to Release',
      'stage:done' => 'Done'
    }
    index = 1;
    defaults.each do |key, val|
      @board.stages.build(github_label: key, name: val, ui_sort_order: index)
      index = index+1
    end
  end

  def create
    @board = Board.new(board_params)
    @board.user = current_user
    if @board.save
      redirect_to board_path(@board)
    else
      render :new
    end
  end

  def show
    @board = Board.friendly.find(params[:id])

    render layout: "kanban"
  end

  def edit
    @board = Board.friendly.find(params[:id])
    session[:return_to] = request.referer
  end

  def update
    @board = Board.friendly.find(params[:id])
    if @board.update_attributes(board_params)
      redirect_to session[:return_to] || board_path(@board)
    else
      render :edit
    end
  end

  def destroy
    board = Board.friendly.find(params[:id])
    board.destroy
    redirect_to boards_path
  end

  def copy
    board = Board.friendly.find(params[:id])

    new_board = board.dup
    new_board.name = "Copy of #{board.name}"
    new_board.save!

    board.repositories.each do |repo|
      new_repo = repo.dup
      new_repo.milestone_id = nil
      new_board.repositories << new_repo
      new_repo.save!
    end

    board.stages.each do |stage|
      new_stage = stage.dup
      new_board.stages << new_stage
      new_stage.save!
    end

    redirect_to edit_board_path(new_board)
  end

  private
    def board_params
      params.require(:board).permit(:name, :milestone, :is_public, :move_other_issues, :move_closed_issues,
                                repositories_attributes: [:id, :url, :_destroy],
                                stages_attributes: [:id, :name, :github_label, :ui_sort_order, :_destroy])
    end

    def reset_return_to
      session[:return_to] = nil
    end
end

app/controllers/concerns/authenticator.rb
module Authenticator
  extend ActiveSupport::Concern

  included do
    if self.to_s != 'SessionController'
      before_action :require_user
    end

    helper_method :current_user
  end

  def require_user
    unless current_user
      store_location
      redirect_to root_path
      return false
    end
  end

  def store_location
    session[:return_to] = request.fullpath
  end

  def redirect_back_or_default(default)
    redirect_to(session[:return_to] || default)
    session[:return_to] = nil
  end
end

app/controllers/kanbans_controller.rb
require 'octokit'

class KanbansController < ApplicationController
  include Authenticator
  include ActionView::Helpers::DateHelper

  def board
    builder = KanbanBoardBuilder.new
    board =  builder.build(current_user, params[:id])

    render json: board.to_json(include: [:repositories, :stages => { :include => :cards}])
  end

  def move_card
    move_card = MoveCard.new(params, current_user)

    render json: move_card.call.number
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  include Authenticator

  def new
    session.delete(:return_to)
    redirect_to boards_url if current_user
  end

  def create
    @user = User.find_or_create_from_auth_hash(auth_hash)
    session[:user_id] = @user.id
    redirect_back_or_default boards_url
  end

  def destroy
    session[:user_id] = nil
    session.delete(:return_to)
    redirect_to root_url
  end

  protected

    def auth_hash
      request.env['omniauth.auth']
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/_board.html.haml
.form-group
  = f.label :name, class: 'col-sm-2 control-label'
  .col-sm-3
    = f.text_field :name, class:'form-control'
.form-group
  = f.label :milestone, class: 'col-sm-2 control-label'
  .col-sm-2
    = f.text_field :milestone, class:'form-control'
.form-group
  .col-sm-offset-2.col-sm-10
    .checkbox
      = f.label :is_public do
        = f.check_box :is_public
        Make this board public

%fieldset
  %legend
    Github Repos
  #repos
    = f.fields_for :repositories do |repo_form|
      .form-group
        = repo_form.label :url, "Repo name", class: 'col-sm-2 control-label'
        .col-sm-4
          = repo_form.text_field :url, class: 'form-control', placeholder: 'e.g. collectivemedia/reachui'
        .col-sm-3
          = repo_form.link_to_remove "", class:'btn btn-danger fa fa-trash'
.form-group
  .col-sm-offset-2.col-sm-10
    = f.link_to_add "Add a repo", :repositories, data:{ target: "#repos" }, class:'btn btn-default'

%fieldset
  %legend
    Kanban Board Stages
  #stages
    = f.fields_for :stages do |stage_form|
      .form-group
        = stage_form.label :github_label, "Stage", class: 'col-sm-2 control-label'
        .col-sm-2
          = stage_form.text_field :github_label, class: 'form-control', placeholder: 'Github label name'
        .col-sm-2
          = stage_form.text_field :name, class: 'form-control', placeholder: 'Stage name'
          = stage_form.hidden_field :ui_sort_order, class: 'form-control ui-sort', placeholder: 'Sort order'
        .col-sm-3
          = stage_form.link_to_remove "", class:'btn btn-danger fa fa-trash'
.form-group
  .col-sm-offset-2.col-sm-10
    = f.link_to_add "Add a stage", :stages, data:{ target: "#stages" }, class:'btn btn-default'

.form-group
  .col-sm-offset-2.col-sm-10
    .checkbox
      = f.label :move_other_issues do
        = f.check_box :move_other_issues
        Move other labeled issues to first stage.
.form-group
  .col-sm-offset-2.col-sm-10
    .checkbox
      = f.label :move_closed_issues do
        = f.check_box :move_closed_issues
        Move closed issues to last stage.


%hr

:javascript
  $(function() {

    $(document).on('nested:fieldAdded:stages', function(event) {
      var field = event.field.find(".ui-sort");
      field[0].value = ++count;

      console.log(field);
    });

    var elms = $(".ui-sort");
    var count = 0;
    if(elms) {
      count = parseInt(elms[elms.length-1].value);
    }
  });

app/views/boards/_board_card.html.haml
- bboards.each_with_index do |board, index|
  .col-sm-6
    .board-block
      .board-left.pull-left
        %img#user.round-profile-img{:src => "#{board.user.image_url}",
          :width => "32", :height => "32", title: "#{board.user.name}", rel: "tooltip-right"}
        .actions
          = link_to board_path(board), title: 'Edit Board', rel: "tooltip-right" do
            = icon("edit")
          = link_to copy_board_path(board), title: 'Copy Board', rel: "tooltip-right" do
            = icon("copy")
          / = link_to board_path(board), confirm: "Are you sure?", method: :delete, title: 'Delete Board' do
          /   = icon("times")
      %div
        %h4
          / = link_to(board.name.strip, kanban_board_path(board.name), class: 'page-title')
        %span
          = board.milestone

app/views/boards/_board_list.html.haml
- bboards.each_with_index do |board, index|
  .board-list-cell
    .row
      .col-md-1
        %img#user.round-rect-img{:src => "#{board.user.image_url}",
            :width => "32", :height => "32", title: "#{board.user.name}", rel: "tooltip-top"}
      .col-md-11
        .name
          = link_to(board.name.strip, board_path(board))
        .clearfix
        .actions
          = link_to edit_board_path(board), class: 'action-button' do
            = icon("edit")
            Edit
          &nbsp;
          = link_to copy_board_path(board), class: 'action-button' do
            = icon("copy")
            Duplicate

app/views/boards/edit.html.haml
= content_for :page_header do
  EDIT BOARD

%div
  &nbsp;
- if flash[:error]
  .form-error
    = flash[:error]
= nested_form_for @board, html: {class: 'form-horizontal', role: 'form'} do |form|
  - if @board.errors.any?
    .form-error
      %h4
        Error(s) saving board:
      %ul
        - @board.errors.full_messages.each do |msg|
          %li
            = msg

  = render "board", f: form
  = form.submit "Save", class: 'btn btn-success'
  &nbsp;
  = link_to 'Delete', board_path(@board), confirm: "Are you sure?", method: :delete, title: 'Delete Board', class: 'btn btn-danger'
  &nbsp;
  = link_to 'Close', session[:return_to], class:'btn btn-default'

&nbsp;
&nbsp;

app/views/boards/index.html.haml
= content_for :page_header do
  BOARDS
= content_for :tool_bar do
  = link_to new_board_path, class:'btn pull-right toolbar-button' do
    = icon("plus")
    Create Board

%div
  &nbsp;
.row
  .col-md-6
    %h4.board-col-header
      %span
        Private Boards
    .board-list
      = render "board_list", bboards: @boards

  .col-md-6
    %h4.board-col-header
      %span
        Public Boards
    .board-list
      = render "board_list", bboards: @public_boards

:javascript

app/views/boards/new.html.haml
= content_for :page_header do
  NEW BOARD

%div
  &nbsp;

= nested_form_for @board, html: {class: 'form-horizontal', role: 'form'} do |form|
  - if @board.errors.any?
    .form-error
      %h4
        Error(s) creating board:
      %ul
        - @board.errors.full_messages.each do |msg|
          %li
            = msg

  = render "board", f: form
  = form.submit "Create", class: 'btn btn-success'
  &nbsp;
  = link_to 'Close', boards_path, class:'btn btn-default'

app/views/boards/show.html.haml
:javascript
  window.APP_URLS = {
    "BOARD" : "#{kanban_board_path(@board.slug)}",
    "EDIT_BOARD": "#{edit_board_path(@board)}",
    "MOVE_CARD" : "#{move_card_path(@board.slug)}",
    "CURRENT_USER_IMG" : "#{current_user.image_url}"
  };

  renderBoard();

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Github Kanban
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container-fluid
      .row.app-header-bg
        .col-sm-6
          %h4
            = yield(:page_header)
        .col-sm-5
          = yield(:tool_bar)

        .col-sm-1
          - if current_user
            = link_to signout_path, class: 'pull-right', title: 'Signout', rel: "tooltip-left" do
              %img#user.round-profile-img{:src => "#{current_user.image_url}", :width => "32", :height => "32"}

    #main-container.container-fluid
      = yield
:javascript
  $(document).ready(function(){
    $("[rel=tooltip-left]").tooltip({ placement: 'left'});
    $("[rel=tooltip-top]").tooltip({ placement: 'top'});
  });

app/views/layouts/kanban.html.haml
!!!
%html
  %head
    %title Github Kanban
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    #main-container
      = yield

app/views/session/new.html.haml
.row
  .col-md-12
    %h1.head-text
      GitHub Issues Kanban View
    .sign-in-with-github
      - if current_user
        = "Welcome #{current_user.name}"
      - else
        %a.btn.btn-default.btn-lg{href: "/auth/github"}
          = image_tag("GitHub_Mark_32px.png")
          Sign in with Github

        -# = link_to "Sign in with Github", "/auth/github", class: 'btn btn-default' do
        -#   = image_tag("GitHub_Mark_64px.png")